spring:
  datasource:
    username: postgres
    password: pgpass
    url: jdbc:postgresql://storagedb.skynet:5432/
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update

management:
  endpoints.web.exposure.include: prometheus
  endpoint.health.show-details: always
  metrics.tags.application: MonitoringSpringDemoProject